# SPDX-License-Identifier: GPL-2.0
dvb-usb-objs += dvb-usb-firmware.o dvb-usb-init.o dvb-usb-urb.o dvb-usb-i2c.o
dvb-usb-objs += dvb-usb-dvb.o dvb-usb-remote.o usb-urb.o
obj-$(CONFIG_DVB_USB) += dvb-usb.o

dvb-usb-technisat-usb2-objs := technisat-usb2.o
obj-$(CONFIG_DVB_USB_TECHNISAT_USB2) += dvb-usb-technisat-usb2.o

dvb-usb-tbsqbox-objs = tbs-qbox.o
obj-$(CONFIG_DVB_USB_TBSQBOX) += dvb-usb-tbsqbox.o

dvb-usb-tbsqbox2-objs = tbs-qbox2.o
obj-$(CONFIG_DVB_USB_TBSQBOX2) += dvb-usb-tbsqbox2.o

dvb-usb-tbsqbox22-objs = tbs-qbox22.o
obj-$(CONFIG_DVB_USB_TBSQBOX22) += dvb-usb-tbsqbox22.o

dvb-usb-tbs5922se-objs = tbs5922se.o
obj-$(CONFIG_DVB_USB_TBS5922SE) += dvb-usb-tbs5922se.o

dvb-usb-tbsqboxs2-objs = tbs-qboxs2.o
obj-$(CONFIG_DVB_USB_TBSQBOXS2) += dvb-usb-tbsqboxs2.o

dvb-usb-tbsqbox2ci-objs = tbs-qbox2ci.o
obj-$(CONFIG_DVB_USB_TBSQBOX2CI) += dvb-usb-tbsqbox2ci.o

dvb-usb-tbs5925-objs = tbs5925.o
obj-$(CONFIG_DVB_USB_TBS5925) += dvb-usb-tbs5925.o

dvb-usb-tbs5880-objs = tbs5880.o
obj-$(CONFIG_DVB_USB_TBS5880) += dvb-usb-tbs5880.o

dvb-usb-tbs5220-objs = tbs5220.o
obj-$(CONFIG_DVB_USB_TBS5220) += dvb-usb-tbs5220.o

dvb-usb-tbs5881-objs = tbs5881.o
obj-$(CONFIG_DVB_USB_TBS5881) += dvb-usb-tbs5881.o

dvb-usb-tbs5520-objs := tbs5520.o
obj-$(CONFIG_DVB_USB_TBS5520) += dvb-usb-tbs5520.o

dvb-usb-tbs5520se-objs = tbs5520se.o
obj-$(CONFIG_DVB_USB_TBS5520se) += dvb-usb-tbs5520se.o

dvb-usb-tbs5580-objs = tbs5580.o
obj-$(CONFIG_DVB_USB_TBS5580) += dvb-usb-tbs5580.o

dvb-usb-tbs5927-objs = tbs5927.o
obj-$(CONFIG_DVB_USB_TBS5927) += dvb-usb-tbs5927.o

dvb-usb-tbs5301-objs = tbs5301.o
obj-$(CONFIG_DVB_USB_TBS5301) += dvb-usb-tbs5301.o

dvb-usb-tbs5930-objs = tbs5930.o
obj-$(CONFIG_DVB_USB_TBS5930) += dvb-usb-tbs5930.o


dvb-usb-tbs5590-objs = tbs5590.o
obj-$(CONFIG_DVB_USB_TBS5590) += dvb-usb-tbs5590.o

ccflags-y += -I$(KBUILD_EXTMOD)/frontends/
# due to tuner-xc3028
ccflags-y += -I$(KBUILD_EXTMOD)/tuners

